pub mod app;
pub mod calendar;
pub mod dashboard;
pub mod domain;
pub mod error;
pub mod event;
pub mod executor;
pub mod gitlab;
pub mod ids;
pub mod matcher;
pub mod planner;
pub mod scheduler;
pub mod server;
pub mod showcase;
pub mod state;
pub mod store;
mod tracker;
pub mod tui;
pub mod worker;
pub mod worktree;

pub use app::MambaApp;
pub use error::{MambaError, Result};
